baseurl = "https://zmaillard.github.io/"
languageCode = "en-us"
title = "Zach Maillard"
theme = "hugo-coder"


[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params]
    author = "Zach Maillard"
    description = "Zach Maillard's personal website"
    keywords = "blog,developer,personal,travel"
    info = "Developer.  Cartographer.  Wanderer."
    avatarurl = "images/avatar.jpg"

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false
    since = 2019

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/zmaillard/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 2
    url = "https://twitter.com/sagebrushgis/"
[[params.social]]
    name = "Keybase"
    icon = "fab fa-keybase"
    weight = 3
    url = "https://keybase.io/sagebrushgis"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/zachmaillard"


[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "https://travels.sagebrushgis.com"

            [[languages.en.menu.main]]
            name = "Signs"
            weight = 3
            url = "https://roadsign.pictures"

            [[languages.en.menu.main]]
            name = "Idaho Maps"
            weight = 4
            url = "http://idahohighway.com"

